# Generated by Django 4.1.7 on 2023-03-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryUser', '0002_about_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
