# Generated by Django 4.1.7 on 2023-03-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0004_gallery_created_alter_gallery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
